export function renderInitGuide({ actionRef = 'v0' } = {}) {
  return [
    '# Agentic Workflow Guard Setup',
    '',
    'Create `.github/workflows/awguard.yml`:',
    '',
    '```yaml',
    `name: Agentic Workflow Guard`,
    '',
    'on:',
    '  pull_request:',
    '  workflow_dispatch:',
    '  schedule:',
    "    - cron: '17 4 * * 1'",
    '',
    'permissions:',
    '  contents: read',
    '  security-events: write',
    '',
    'jobs:',
    '  scan:',
    '    runs-on: ubuntu-latest',
    '    steps:',
    '      - uses: actions/checkout@v6',
    `      - uses: Mughal-Baig/agentic-workflow-guard@${actionRef}`,
    '        with:',
    '          preset: strict',
    '          format: sarif',
    '          output: awguard.sarif',
    '          fail-on: high',
    '      - uses: github/codeql-action/upload-sarif@v4',
    '        if: always()',
    '        with:',
    '          sarif_file: awguard.sarif',
    '          category: agentic-workflow-guard',
    '```',
    '',
    'Create `awguard.config.json`:',
    '',
    '```json',
    JSON.stringify(
      {
        $schema:
          'https://raw.githubusercontent.com/Mughal-Baig/agentic-workflow-guard/main/schemas/awguard.config.schema.json',
        extends: ['strict'],
        policy: {
          approvedFiles: ['AGENTS.md', '.github/workflows/*'],
          approvedMcpServers: [],
          approvedMcpPackages: [],
          approvedMcpCommands: ['npx', 'node', 'uvx', 'docker']
        },
        suppressions: {
          minimumReasonLength: 20
        }
      },
      null,
      2
    ),
    '```',
    '',
    'Adopt without breaking existing CI:',
    '',
    '```bash',
    'npx awguard@latest . --write-baseline awguard.baseline.json --fail-on none',
    'npx awguard@latest . --baseline awguard.baseline.json --fail-on high',
    '```',
    '',
    'Generate useful reports:',
    '',
    '```bash',
    'npx awguard@latest . --format inventory',
    'npx awguard@latest . --format inventory-json --output awguard-inventory.json',
    'npx awguard@latest . --format score',
    'npx awguard@latest . --format badge --output docs/awguard-badge.json',
    '```',
    '',
    'README badge:',
    '',
    '```markdown',
    '[![AWI risk](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/OWNER/REPO/main/docs/awguard-badge.json)](docs/awguard-badge.json)',
    '```'
  ].join('\n');
}
